// <auto-generated />
namespace ASM2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _193 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_193));
        
        string IMigrationMetadata.Id
        {
            get { return "202110191512421_193"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
