// <auto-generated />
namespace ASM2.EF.FPTMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddCatId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCatId));
        
        string IMigrationMetadata.Id
        {
            get { return "202110071453195_AddCatId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
